version: "3.6"
services:
  gameserver:
    build:
      context: .
      dockerfile: ./docker/gameserver/Dockerfile
    command: nodemon npm start
    volumes:
      - ./gameserver:/usr/src/app/
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "80:1337"